name: AUTO_BUILD_APK
on: [push, workflow_dispatch] # Builds every time you save OR click a button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build My App
        run: |
          flutter pub get
          flutter build apk --release --split-per-abi

      - name: Create Download Link
        uses: actions/upload-artifact@v4
        with:
          name: TV_APP_FINAL
          path: build/app/outputs/flutter-apk/*.apk
